__title__ = "plyflatten"
__description__ = "Take a series of ply files and produce a digitial elevation map"
__url__ = "https://github.com/cmla/plyflatten"
__author__ = """Carlo de Franchis"""
__author_email__ = "carlo.de-franchis@ens-cachan.fr"
__version__ = "0.1.0dev"
